################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/utility/m2.cpp \
../src/utility/m2align.cpp \
../src/utility/m2dfs.cpp \
../src/utility/m2draw.cpp \
../src/utility/m2eh2bd.cpp \
../src/utility/m2eh2bs.cpp \
../src/utility/m2eh4bd.cpp \
../src/utility/m2eh4bs.cpp \
../src/utility/m2eh6bs.cpp \
../src/utility/m2ehts.cpp \
../src/utility/m2el2lmenu.cpp \
../src/utility/m2elalign.cpp \
../src/utility/m2elbutton.cpp \
../src/utility/m2elbuttonptr.cpp \
../src/utility/m2elcombo.cpp \
../src/utility/m2elcombofn.cpp \
../src/utility/m2elcomboptr.cpp \
../src/utility/m2elfnfmt.cpp \
../src/utility/m2elhide.cpp \
../src/utility/m2elinfo.cpp \
../src/utility/m2ellabel.cpp \
../src/utility/m2ellabelfn.cpp \
../src/utility/m2ellabelp.cpp \
../src/utility/m2ellabelptr.cpp \
../src/utility/m2ellistbase.cpp \
../src/utility/m2ellistcalc.cpp \
../src/utility/m2ellistgrid.cpp \
../src/utility/m2ellisth.cpp \
../src/utility/m2ellistv.cpp \
../src/utility/m2ellistxy.cpp \
../src/utility/m2elradio.cpp \
../src/utility/m2elroot.cpp \
../src/utility/m2els8base.cpp \
../src/utility/m2els8num.cpp \
../src/utility/m2elsb.cpp \
../src/utility/m2elsetval.cpp \
../src/utility/m2elslbase.cpp \
../src/utility/m2elspace.cpp \
../src/utility/m2elstr.cpp \
../src/utility/m2elstrlist.cpp \
../src/utility/m2elstrptr.cpp \
../src/utility/m2elstrup.cpp \
../src/utility/m2elsubutl.cpp \
../src/utility/m2eltext.cpp \
../src/utility/m2eltoggle.cpp \
../src/utility/m2eltsk.cpp \
../src/utility/m2elu32.cpp \
../src/utility/m2elu8base.cpp \
../src/utility/m2elu8hs.cpp \
../src/utility/m2elu8num.cpp \
../src/utility/m2elxbm.cpp \
../src/utility/m2esarduino.cpp \
../src/utility/m2esserial.cpp \
../src/utility/m2fnarg.cpp \
../src/utility/m2gfx.cpp \
../src/utility/m2gfxutl.cpp \
../src/utility/m2ghdummy.cpp \
../src/utility/m2ghserial.cpp \
../src/utility/m2ghu8gbf.cpp \
../src/utility/m2ghu8gbfs.cpp \
../src/utility/m2ghu8gcffs.cpp \
../src/utility/m2ghu8gfb.cpp \
../src/utility/m2ghu8gffs.cpp \
../src/utility/m2ghu8gicon.cpp \
../src/utility/m2ghu8gutl.cpp \
../src/utility/m2key.cpp \
../src/utility/m2msg.cpp \
../src/utility/m2navdatadn.cpp \
../src/utility/m2navdataup.cpp \
../src/utility/m2navfirst.cpp \
../src/utility/m2navinit.cpp \
../src/utility/m2navlast.cpp \
../src/utility/m2navnext.cpp \
../src/utility/m2navprev.cpp \
../src/utility/m2navroot.cpp \
../src/utility/m2navupdn.cpp \
../src/utility/m2navutl.cpp \
../src/utility/m2null.cpp \
../src/utility/m2obj.cpp \
../src/utility/m2opt.cpp \
../src/utility/m2pin.cpp \
../src/utility/m2qk.cpp \
../src/utility/m2rom.cpp \
../src/utility/m2usrnext.cpp \
../src/utility/m2usrprev.cpp \
../src/utility/m2usrupdn.cpp \
../src/utility/m2utls8d.cpp \
../src/utility/m2utlstrdat.cpp \
../src/utility/m2utlu8d.cpp \
../src/utility/mas.cpp \
../src/utility/mas_pff.cpp \
../src/utility/mas_sim.cpp \
../src/utility/pff.cpp \
../src/utility/pff_arduino_io.cpp \
../src/utility/pff_diskio.cpp 

OBJS += \
./src/utility/m2.o \
./src/utility/m2align.o \
./src/utility/m2dfs.o \
./src/utility/m2draw.o \
./src/utility/m2eh2bd.o \
./src/utility/m2eh2bs.o \
./src/utility/m2eh4bd.o \
./src/utility/m2eh4bs.o \
./src/utility/m2eh6bs.o \
./src/utility/m2ehts.o \
./src/utility/m2el2lmenu.o \
./src/utility/m2elalign.o \
./src/utility/m2elbutton.o \
./src/utility/m2elbuttonptr.o \
./src/utility/m2elcombo.o \
./src/utility/m2elcombofn.o \
./src/utility/m2elcomboptr.o \
./src/utility/m2elfnfmt.o \
./src/utility/m2elhide.o \
./src/utility/m2elinfo.o \
./src/utility/m2ellabel.o \
./src/utility/m2ellabelfn.o \
./src/utility/m2ellabelp.o \
./src/utility/m2ellabelptr.o \
./src/utility/m2ellistbase.o \
./src/utility/m2ellistcalc.o \
./src/utility/m2ellistgrid.o \
./src/utility/m2ellisth.o \
./src/utility/m2ellistv.o \
./src/utility/m2ellistxy.o \
./src/utility/m2elradio.o \
./src/utility/m2elroot.o \
./src/utility/m2els8base.o \
./src/utility/m2els8num.o \
./src/utility/m2elsb.o \
./src/utility/m2elsetval.o \
./src/utility/m2elslbase.o \
./src/utility/m2elspace.o \
./src/utility/m2elstr.o \
./src/utility/m2elstrlist.o \
./src/utility/m2elstrptr.o \
./src/utility/m2elstrup.o \
./src/utility/m2elsubutl.o \
./src/utility/m2eltext.o \
./src/utility/m2eltoggle.o \
./src/utility/m2eltsk.o \
./src/utility/m2elu32.o \
./src/utility/m2elu8base.o \
./src/utility/m2elu8hs.o \
./src/utility/m2elu8num.o \
./src/utility/m2elxbm.o \
./src/utility/m2esarduino.o \
./src/utility/m2esserial.o \
./src/utility/m2fnarg.o \
./src/utility/m2gfx.o \
./src/utility/m2gfxutl.o \
./src/utility/m2ghdummy.o \
./src/utility/m2ghserial.o \
./src/utility/m2ghu8gbf.o \
./src/utility/m2ghu8gbfs.o \
./src/utility/m2ghu8gcffs.o \
./src/utility/m2ghu8gfb.o \
./src/utility/m2ghu8gffs.o \
./src/utility/m2ghu8gicon.o \
./src/utility/m2ghu8gutl.o \
./src/utility/m2key.o \
./src/utility/m2msg.o \
./src/utility/m2navdatadn.o \
./src/utility/m2navdataup.o \
./src/utility/m2navfirst.o \
./src/utility/m2navinit.o \
./src/utility/m2navlast.o \
./src/utility/m2navnext.o \
./src/utility/m2navprev.o \
./src/utility/m2navroot.o \
./src/utility/m2navupdn.o \
./src/utility/m2navutl.o \
./src/utility/m2null.o \
./src/utility/m2obj.o \
./src/utility/m2opt.o \
./src/utility/m2pin.o \
./src/utility/m2qk.o \
./src/utility/m2rom.o \
./src/utility/m2usrnext.o \
./src/utility/m2usrprev.o \
./src/utility/m2usrupdn.o \
./src/utility/m2utls8d.o \
./src/utility/m2utlstrdat.o \
./src/utility/m2utlu8d.o \
./src/utility/mas.o \
./src/utility/mas_pff.o \
./src/utility/mas_sim.o \
./src/utility/pff.o \
./src/utility/pff_arduino_io.o \
./src/utility/pff_diskio.o 

CPP_DEPS += \
./src/utility/m2.d \
./src/utility/m2align.d \
./src/utility/m2dfs.d \
./src/utility/m2draw.d \
./src/utility/m2eh2bd.d \
./src/utility/m2eh2bs.d \
./src/utility/m2eh4bd.d \
./src/utility/m2eh4bs.d \
./src/utility/m2eh6bs.d \
./src/utility/m2ehts.d \
./src/utility/m2el2lmenu.d \
./src/utility/m2elalign.d \
./src/utility/m2elbutton.d \
./src/utility/m2elbuttonptr.d \
./src/utility/m2elcombo.d \
./src/utility/m2elcombofn.d \
./src/utility/m2elcomboptr.d \
./src/utility/m2elfnfmt.d \
./src/utility/m2elhide.d \
./src/utility/m2elinfo.d \
./src/utility/m2ellabel.d \
./src/utility/m2ellabelfn.d \
./src/utility/m2ellabelp.d \
./src/utility/m2ellabelptr.d \
./src/utility/m2ellistbase.d \
./src/utility/m2ellistcalc.d \
./src/utility/m2ellistgrid.d \
./src/utility/m2ellisth.d \
./src/utility/m2ellistv.d \
./src/utility/m2ellistxy.d \
./src/utility/m2elradio.d \
./src/utility/m2elroot.d \
./src/utility/m2els8base.d \
./src/utility/m2els8num.d \
./src/utility/m2elsb.d \
./src/utility/m2elsetval.d \
./src/utility/m2elslbase.d \
./src/utility/m2elspace.d \
./src/utility/m2elstr.d \
./src/utility/m2elstrlist.d \
./src/utility/m2elstrptr.d \
./src/utility/m2elstrup.d \
./src/utility/m2elsubutl.d \
./src/utility/m2eltext.d \
./src/utility/m2eltoggle.d \
./src/utility/m2eltsk.d \
./src/utility/m2elu32.d \
./src/utility/m2elu8base.d \
./src/utility/m2elu8hs.d \
./src/utility/m2elu8num.d \
./src/utility/m2elxbm.d \
./src/utility/m2esarduino.d \
./src/utility/m2esserial.d \
./src/utility/m2fnarg.d \
./src/utility/m2gfx.d \
./src/utility/m2gfxutl.d \
./src/utility/m2ghdummy.d \
./src/utility/m2ghserial.d \
./src/utility/m2ghu8gbf.d \
./src/utility/m2ghu8gbfs.d \
./src/utility/m2ghu8gcffs.d \
./src/utility/m2ghu8gfb.d \
./src/utility/m2ghu8gffs.d \
./src/utility/m2ghu8gicon.d \
./src/utility/m2ghu8gutl.d \
./src/utility/m2key.d \
./src/utility/m2msg.d \
./src/utility/m2navdatadn.d \
./src/utility/m2navdataup.d \
./src/utility/m2navfirst.d \
./src/utility/m2navinit.d \
./src/utility/m2navlast.d \
./src/utility/m2navnext.d \
./src/utility/m2navprev.d \
./src/utility/m2navroot.d \
./src/utility/m2navupdn.d \
./src/utility/m2navutl.d \
./src/utility/m2null.d \
./src/utility/m2obj.d \
./src/utility/m2opt.d \
./src/utility/m2pin.d \
./src/utility/m2qk.d \
./src/utility/m2rom.d \
./src/utility/m2usrnext.d \
./src/utility/m2usrprev.d \
./src/utility/m2usrupdn.d \
./src/utility/m2utls8d.d \
./src/utility/m2utlstrdat.d \
./src/utility/m2utlu8d.d \
./src/utility/mas.d \
./src/utility/mas_pff.d \
./src/utility/mas_sim.d \
./src/utility/pff.d \
./src/utility/pff_arduino_io.d \
./src/utility/pff_diskio.d 


# Each subdirectory must supply rules for building sources it contributes
src/utility/%.o: ../src/utility/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C++ Compiler'
	arm-none-eabi-c++ -D__NEWLIB__ -DDEBUG -D__CODE_RED -DCORE_M0 -D__USE_LPCOPEN -D__LPC11XX__ -I"C:\Users\Olli\CloudStation\uC_Stuff\LPC_workspaces\neuneu_software-arm-olli\M2tklib\inc" -I"C:\Users\Olli\CloudStation\uC_Stuff\LPC_workspaces\neuneu_software-arm-olli\u8g_lib\inc" -I"C:\Users\Olli\CloudStation\uC_Stuff\LPC_workspaces\neuneu_software-arm-olli\CMSIS_CORE_LPC11xx\inc" -I"C:\Users\Olli\CloudStation\uC_Stuff\Selfbus\software-arm-lib\sblib\inc" -O0 -g3 -Wall -c -fmessage-length=0 -fno-builtin -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -mcpu=cortex-m0 -mthumb -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


